channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python==3.12
  - r-base==4.4.3
  - r-remotes==2.5.0
  # sequenza requirements (+copynumber)
  - r-pbapply==1.7_2
  - r-squash==1.0.9
  - r-iotools==0.3_2  # See https://bitbucket.org/sequenzatools/sequenza/pull-requests/3
  - r-readr==2.1.5
  - r-pbapply=1.7
  - r-squash==1.0.9
  - r-iotools==0.3_5
  - r-seqminer==9.4
  - r-ks==1.15.1
  - r-digest==0.6.37
  - pandoc==3.7
  # Missing: Runuran (on CRAN, not on conda-forge)
  - r-curl==6.4.0    # Not required, but avoids readr warnings
