channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python==3.12
  - r-base==4.3.3
  - r-remotes==2.5.0
  # sequenza requirements (+copynumber)
  - r-pbapply==1.7_2
  - r-squash==1.0.9
  - r-iotools==0.3_2  # See https://bitbucket.org/sequenzatools/sequenza/pull-requests/3
  - r-readr==2.1.5
  - r-seqminer==9.4
  - r-data.table==1.15.2
  # copynumber requirements
  - bioconductor-s4vectors==0.40.2
  - bioconductor-iranges==2.36.0
  - bioconductor-genomicranges==1.54.1

